"""bug fix for courtes relationship

Revision ID: fda5c6444af5
Revises: 8b9108e07f53
Create Date: 2024-11-29 03:31:43.623629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda5c6444af5'
down_revision = '8b9108e07f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
