JSON_CONTENT_TYPE = "application/json"


# users api responses
INVALID_ACCESS_TOKEN = "Please provide a valid access token."
INVALID_ACTIVATION_TOKEN = "Invalid activation token."
INVALID_REFRESH_TOKEN = "Invalid refresh token."
INVALID_RESET_TOKEN = "Invalid reset token."
INVALID_CREDENTIALS = "Invalid credentials."
LOGIN_FAILED = "Login failed."
LOGIN_SUCCESSFUL = "Login successful."
LOGOUT_FAILED = "Logout failed."
LOGOUT_SUCCESSFUL = "Logout successful."
NON_VALIDATED_USER = "User is not validated. Please verify your email."
PASSWORD_RESET_EMAIL_SENT = "Password reset email sent."
PASSWORD_RESET_EMAIL_FAILED = "Password reset email failed."
PASSWORD_RESET_FAILED = "Password reset failed."
PASSWORD_RESET_SUCCESSFUL = "Password reset successful."
TOKEN_REFRESH_FAILED = "Token refresh failed."
TOKEN_REFRESH_SUCCESSFUL = "Token refresh successful."
UNKNOWN_USER = "User does not exist."
USER_ACTIVATION_FAILED = "Activation failed."
USER_ACTIVATION_SUCCESSFUL = "User successfully activated."
USER_ALREADY_ACTIVATED = "User is already activated. Please login."
USER_ALREADY_EXISTS = "User already exists."
USER_REGISTRATION_SUCCESSFUL = "User successfully created."
USER_REGISTRATION_FAILED = "User registration failed."
USER_REGISTRATION_DUPLICATE = "This email address is already registered in Muchbetter."
USER_LOAD_FAILED = "User load failed."
USER_LOAD_SUCCESSFUL = "User load successful."
USER_NOT_ACTIVE = "User is not active. Please login."
USER_NOT_AUTHORIZED = "User is not authorized to access the resource."
USER_UPDATE_SUCCESSFUL = "User update successful"
USER_UPDATE_FAILED = "User update failed"
USER_CREATE_SUCCESSFUL = "User create successful"
USER_CREATE_FAILED = "User create failed"
PASSWORD_NOT_SET = "Password is not set."

# cases api responses
CASE_ALREADY_EXISTS = "Case already exists"
CASE_CREATION_SUCCESSFUL = "Case create successful"
CASE_CREATION_FAILED = "Case create failed"
UNKNOWN_CASE = "Case does not exist"
DOCUMENT_COUNT_EXCEEDS = "Documents count exceeds"
DOCUMENT_UPLOAD_SUCCESSFUL = "Documents upload successful"
DOCUMENT_UPLOAD_FAILED = "Documents upload failed "